students_project/students_app/api/urls.py
from django.urls import re_path, include
from .views import (StuListApiView, StuDetailApiView)

urlpatterns=[
    re_path('', StuListApiView.as_view()),
    re_path('<int:student_id>/', StuDetailApiView.as_view()),
]

students_project/students_app/urls.py
from django.urls import re_path, include
from . import views

app_name = 'students_app'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),

    re_path(r'^(?P<student_id>[0-9]+)/$', views.detail, name='detail'),
    re_path(r'details/(?P<student_id>[0-9]+)/$', views.detail, name='detail'),

    re_path(r'^add$', views.add, name='add'),
    re_path(r'^getAdd$', views.getAdd, name='getAdd'),

    re_path('api/', include('students_app.api.urls'))

]

students_project/students_project/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^students_app/', include('students_app.urls')),
    
]

students_project/students_app/models.py
from django.db import models

# Create your models here.

class Students(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    address = models.CharField(max_length=100)
    mobile_number = models.CharField(max_length=11)

    def __str__(self):
        return self.name

    
class Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

students_project/students_app/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from students_app.models import Students
from .serializer import StuSerializer

class StuListApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]

#  get the list of Student
    def get(self, request, *args, **kwargs):
        students = Students.objects.filter(student = request.student.id)
        serializer = StuSerializer(students, many = True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    
#  add 
    def post(self, request, *args, **kwargs ):
        data = {
            'id': request.data.get('id'),
            'name': request.data.get('name'),
            'age': request.data.get('age'),
            'address': request.data.get('address'),
            'mobile_number': request.data.get('mobile_number')
        }
        serializer = StuSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

class StuDetailApiView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    def get_object(self, student_id):
        try:
            return Students.objects(id=student_id)
        except Students.DoesNotExist:
            return None

    def get(self, student_id, *args, **kwargs):
        stu_instance = self.get_object(student_id)
        if not stu_instance:
            return Response(
                {"res":"Object with todo id does not exists"},
                status = status.HTTP_400_BAD_REQUEST
            )

        serializer = StuSerializer(stu_instance)
        return Response(serializer.data, status=status.HTTP_200_OK) 


# edit
    def put(self, request, student_id, *args, **kwargs):
        stu_instance = self.get_object(student_id)
        if not stu_instance:
            return Response(
                {"res": "Object student id does not exists"},
                status=status.HTTP_400_BAD_REQUEST
            )
        data = {
            'id': request.data.get('id'),
            'name': request.data.get('name'),
            'age': request.data.get('age'),
            'address': request.data.get('address'),
            'mobile_number': request.data.get('mobile_number')
        }
        serializer = StuSerializer(instance = stu_instance, data=data, partial= True)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# delete
    def delete(self, student_id):
        stu_instance = self.get_object(student_id)
        if not stu_instance:

            return Response(
                {"res": "Object doesn't not exists"},
                status=status.HTTP_400_BAD_REQUEST
            )
        stu_instance.delete()
        return Response(
            {"res": "Object deleted!"},
            status=status.HTTP_200_OK
        )

students_project/students_app/views.py
from django.shortcuts import render

from .models import Students
from django.template import loader
from django.http import Http404, HttpResponse
from .form import addStudent

# Create your views here.

def index(request):
    student_list = Students.objects.all()
    template = loader.get_template('students_app/index.html')
    context = {
        'student_list': student_list
    }
    return HttpResponse(template.render(context, request))

def detail(request, student_id):
    try:
        info_student = Students.objects.filter(pk=student_id)
    except Students.DoesNotExist:
        raise Http404('Student is not found')
    return render(request, 'students_app/detail.html', {'info_student': info_student})


def add(request):
    cont = {'uf':addStudent}
    return render(request, 'students_app/add.html', cont )

def getAdd(request):
    if request.method == 'POST':
        uf = addStudent(request.POST)
        if uf.is_valid():
            saveUF = Students(
                id = uf.cleaned_data['id'],
                name = uf.cleaned_data['name'],
                age = uf.cleaned_data['age'],
                address = uf.cleaned_data['address'],
                mobile_number = uf.cleaned_data['mobile_number']
            )
            saveUF.save()
            return HttpResponse('save success')

        else:
            return HttpResponse('form not value')
    else:
        return HttpResponse('not POST')

students_project/students_app/templates/students_app/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add View</title>
</head>

<body>
    <form action="{% url 'students_app:getAdd' %}" method="post"> 
        {% csrf_token %}
        <table>
            {{ uf.as_table }}  
        </table>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

students_project/students_app/templates/students_app/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Detail View</title>
    </head>

    <body>
        <h3 style="color: red;">A STUDENT'S INFORMATION IN THE DATABASE</h3>
    <table border="1">
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Age</td>
                <td>Address</td>
                <td>Mobile_number</td>
            </tr>
        </thead>
        <tbody>
            
            {% for items in info_student %}
            <tr>
                <td>{{ items.id }}</td>
                <td>{{ items.name }}</td>
                <td>{{ items.age }}</td>
                <td>{{ items.address }}</td>
                <td>{{ items.mobile_number }}</td>
            </tr>
            {% endfor %}
            
        </tbody>

    </table>
    </body>

</html>

students_project/students_app/templates/students_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Index View</title>

    </head>

    <body>
        <h3 style="color: red;">ALL STUDENTS IN THE DATABASE</h3>
        {% if student_list %}
        <ul>
            {% for student in student_list %}
            <li>
                <!-- <a href="/students_app/{{student.id}}/"></a> -->
                <a href="{% url 'students_app:detail' student.id %}">
                    {{ student.name }}
                </a>
            </li>
            {% endfor %}
        </ul>

        {% else %}
        <p style="color: red;">No students_app are valilable</p>
        {% endif %}
    </body>

</html>